logging:
  level:
    hnp.selenium.chromedriver: debug
    org.springframework.aop.interceptor: trace
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug

server:
  port: ${PORT:8082}

messages:
  home: Hello, Memorynotfound!

spring:
  application:
    name: chromedriver
    version: 0.0.1
  data:
    mongodb:
      host: ${DB_HOST_MG:localhost}
      port: ${DB_PORT_MG:27017}
      database: ${DB_NAME_MG:coldPenalty}
      repositories:
        enabled: true
      
  messages:
    basename: i18n/messages

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    # excluded-view-names:
    # mode: HTML5
    # prefix: /templates/
    # suffix: .html
    # template-resolver-order:
    # view-names: